# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title
gems:
  - jekyll-paginate
# Setup
title:            MCLEIAN
tagline:          'just another blog'
description:      'My personal blog.'
url:              mcleian.com
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           McLeian Caudilla
  url:            https://mcleian.com/

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

### availavle icons at: https://genericons.com/
social:
  - icon:         twitter
    url:          https://twitter.com/amcmac
    desc:         follow me plz

  - icon:         instagram
    url:          http://instagram.com/amcmac
    desc:         follow me plz

  - icon:         image
    url:          http://amcmac.vsco.co
    desc:         my vsco grid
    
  - icon:         youtube
    url:          http://youtube.com/c/McLeianCaudilla
    desc:         subscribe
    
  - icon:         vimeo
    url:          http://vimeo.com/mcleian
    desc:         watch
    
  - icon:         spotify
    url:          https://open.spotify.com/user/1210230561
    desc:         listen
    
menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /whatisthis
    
  - title:        Journal
    url:          /penandpaper
    
  - title:        Photography
    url:          /lens
    
  - title:        Travel
    url:          /passport
    
  - title:        Music
    url:          /playlist

copyright:
  author:         Camporez
  url:            http://camporez.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         true    ### This makes the cover and icon move when you scroll

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
